In [10]:
import itertools
import cv2
img1 = cv2.imread('static/uploads/1.png',0)
img2 = cv2.imread('static/uploads/2.png',0)
img3 = cv2.imread('static/uploads/output.png',0)
imgs1=[img1,img2,img3]
imgs2=[img1,img2,img3,1,2,3,3]


for f,b in zip(imgs1,imgs2):
    print(b)
# for f,b in itertools.izip_longest(imgs1,imgs2):
#     print(f,b)


[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 244 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [11]:
import numpy as np
x1 = np.array([2, 5, 255])
x2 = np.array([3, 14, 16])
x1 & x2

array([ 2,  4, 16], dtype=int32)

In [ ]:
list=[]]