In [ ]:
# Plotting the results
plt.subplot(131)
plt.imshow(image_rgb)
plt.subplot(132)
plt.imshow(result_rgb2)
plt.subplot(133)
plt.imshow(result_rgb)
plt.show()
import cv2 
img = cv2.imread('../assets/1.png',0)
img = cv2.imread('../assets/1.png',0)
img = cv2.imread('../assets/1.png',0)
img = cv2.imread('../assets/1.png',0)
imageToBeMixed = cv2.imread('../assets/omda.png',0)

variable = img.shape
variable = (variable[1],variable[0])

print(imageToBeMixed.shape)
imageToBeMixed = cv2.resize(imageToBeMixed, variable)
print(imageToBeMixed.shape)


In [103]:
def scale(image_array):
    image = ((image_array - image_array.min()) * (1/(image_array.max() - image_array.min()) * 255)).astype('uint8')
    return image

def update(arr,x1,x2,y1,y2):
        for i in range(arr.shape[0]):
            for j in range(arr.shape[1]):
                if (i < x1 or i>x2 ) or (j<=y1 or j > y2 ):
                    arr[i][j]=1
        return arr

(3, 0)


In [110]:
import cv2 
import numpy as np
from matplotlib import pyplot as plt

def plotFunc(x,s):
    cv2.imwrite(f'{s}.png', x)
    
img = cv2.imread('../code/assets/image2.png',0)
imageToBeMixed = cv2.imread('../code/assets/image2.png',0)

variable = img.shape
variable = (variable[1],variable[0])
imageToBeMixed = cv2.resize(imageToBeMixed, variable)

#IMAGE ONE FOURIER
f = np.fft.fft2(img)
fshift = np.fft.fftshift(f)
magnitude_spectrum = 20*np.log(np.abs(fshift))

#IMAGE TWO FOURIER
f2 = np.fft.fft2(imageToBeMixed)
fshift2 = np.fft.fftshift(f2)
magnitude_spectrum = 20*np.log(np.abs(fshift2))
ang2 = np.angle(fshift2)

#COMBINED IMAGE
M1 = np.abs(fshift)
M1 = update(M1,0,4032,0,3024)
P2 = ang2
P2 = update(P2,0,1000,0,1000)
result  = M1
result2 = P2

combined = np.multiply(result, np.exp(1j * result2))
# f_ishift3 = np.fft.ifftshift(combined)
# img_back = np.fft.ifft2(f_ishift3)
# img_back = np.real(img_back)

mixInverse = np.real(np.fft.ifft2(combined))

plotFunc(mixInverse, "test")


In [104]:
M1.shape

(4032, 3024)

In [85]:
magnitude_spectrum = cv2.imread('../code/static/uploads/1.png')
# create a mask image of the same shape as input image, filled with 0s (black color)
mask = np.zeros_like(magnitude_spectrum)
mask2 = np.zeros_like(magnitude_spectrum)
rows, cols,_ = mask.shape
# create a white filled ellipse
mask   = cv2.ellipse(mask, center=(rows//2, cols//2), axes=(2000,3000), angle=0, startAngle=0, endAngle=360, color=(255,255,255), thickness=-1)
mask2  = cv2.rectangle(mask2, (0,0), (5000,5000), color=(255,255,255), thickness=-1)
# Bitwise AND operation to black out regions outside the mask


mask  = cv2.cvtColor(mask, cv2.COLOR_BGR2GRAY)
magnitude_spectrum  = cv2.cvtColor(magnitude_spectrum, cv2.COLOR_BGR2GRAY)
mask2 = cv2.cvtColor(mask2, cv2.COLOR_BGR2GRAY)

M1 = M1.astype(int)
# M1 = scale(M1)
result  = np.bitwise_and(M1,mask2)
# result2 = M1*mask
# result2 = np.bitwise_and(image,mask2)

# M1 = scale(magnitude_spectrum)

# result  = M1*mask
# result2 = P2*mask2

# Convert from BGR to RGB for displaying correctly in matplotlib
# Note that you needn't do this for displaying using OpenCV's imshow()

plotFunc(result, "test_old")
plotFunc(M1, "test_new")

In [70]:
print(M1)
print("))))))))))))")
print(image)

[[255  13  23 ...   7  23  13]
 [ 53  11  14 ...  14   4   6]
 [ 19   6   4 ...   3   7   2]
 ...
 [ 12   9   5 ...   1   3   2]
 [ 19   2   7 ...   1   4   6]
 [ 53   6   4 ...   2  14  11]]
))))))))))))
[[129 141 140 ... 134 140 141]
 [128 144 145 ... 140 154 148]
 [132 151 125 ... 154 143 143]
 ...
 [155 149 152 ... 142 149 152]
 [132 143 143 ... 129 125 151]
 [128 148 154 ... 126 145 144]]


In [ ]:
# Read an input image as a gray image
img = cv2.imread('../code/assets/image2.png')

# create a mask
mask = np.zeros(img.shape[:2], np.uint8)
mask[100:250, 150:450] = 255

# compute the bitwise AND using the mask
masked_img = cv2.bitwise_and(img,img,mask = mask)

# display the mask, and the output image
plotFunc(mask)
plotFunc(masked_img)